### ISSUE TITLE
Link Dump - Apr 2018

### ISSUE THREAD

**Issue by notshi** [meatstuff/itstuff#19]
**lulz**
- [ ] https://arstechnica.com/gaming/2018/03/cias-in-house-board-games-can-now-be-yours-thanks-to-an-foia-request/
- [ ] https://www.bloomberg.com/news/articles/2018-03-30/magic-leap-ships-first-set-of-devices-under-tight-security-constraints

**general tech**
- [ ] http://www.npl.co.uk/news/npl-scientists-create-diodes-made-of-light
- [ ] https://www.bloomberg.com/news/articles/2018-04-02/apple-is-said-to-plan-move-from-intel-to-own-mac-chips-from-2020
- [ ] https://spaceflightnow.com/2018/04/01/eliminating-space-junk-could-take-step-toward-reality-with-station-cargo-launch/

**world of stuffs**
- [ ] **FUCK YOU VICE** https://twitter.com/alicegoldfuss/status/980948356833755136
- [ ] https://www.theregister.co.uk/2018/03/22/atari_lempty_box/
- [ ] https://hackaday.com/2018/04/03/is-this-the-end-for-the-c-h-i-p/

**youtube of the month**
- [ ] https://www.youtube.com/user/RevisionParty
- [ ] https://www.zerohedge.com/news/2018-04-03/active-shooter-reported-youtube-headquarters

**bitcoin**
- [ ] https://www.lightbluetouchpaper.org/2018/03/26/tracing-stolen-bitcoin/
- [ ] https://motherboard.vice.com/en_us/article/59jzyn/president-donald-trump-signs-executive-order-banning-venezuelas-petro-cryptocurrency-maduro
- [ ] https://www.qarnot.com/crypto-heater_qc1/

**leak**
- [ ] https://github.com/SINTEF-9012/grindr-privacy-leaks
- [ ] 150 mil data breach - https://www.washingtonpost.com/news/the-switch/wp/2018/03/29/under-armour-announces-data-breach-affecting-150-million-myfitnesspal-app-accounts/

**hack**
- [ ] https://www.reuters.com/article/us-usa-cyber-atlanta/with-paper-and-phones-atlanta-struggles-to-recover-from-cyber-attack-idUSKBN1H70R0
- [ ] https://www.thedailybeast.com/exclusive-lone-dnc-hacker-guccifer-20-slipped-up-and-revealed-he-was-a-russian-intelligence-officer
- [ ] http://blog.frizk.net/2018/03/total-meltdown.html?m=1

**ai**
- [ ] https://theintercept.com/2018/03/09/amazon-echo-alexa-uk-police/
- [ ] https://arstechnica.com/cars/2018/03/uber-self-driving-car-hits-and-kills-pedestrian/
- [ ] https://www.wsj.com/articles/tesla-recalls-123-000-model-s-cars-over-bolt-issue-1522361482
- [ ] https://www.technologyreview.com/the-download/610725/microsoft-is-doing-the-splits-to-focus-on-ai-and-the-cloud
- [ ] https://blogs.microsoft.com/ai/microsoft-professional-program-ai/
- [ ] https://www.theguardian.com/technology/2018/mar/22/video-released-of-uber-self-driving-crash-that-killed-woman-in-arizona
- [ ] 'internet of battle things' https://thenextweb.com/artificial-intelligence/2018/04/02/military-documents-reveal-how-the-us-army-plans-to-deploy-ai-in-future-wars

**nature**
- [ ] https://preview.entsoe.eu/news/2018/03/06/press-release-continuing-frequency-deviation-in-the-continental-european-power-system-originating-in-serbia-kosovo-political-solution-urgently-needed-in-addition-to-technical/
- [ ] https://www.anandtech.com/show/12535/power-outage-at-samsungs-fab-destroys-3-percent-of-global-nand-flash-output
- [ ] http://www.harrowell.org.uk/blog/2018/03/21/network-structure-fake-news-and-why-nice-people-dont-go-nazi/

**law**
- [ ] https://www.theguardian.com/technology/2018/feb/06/gdpr-data-protection-law-scammers-whois-tools-internet-european-privacy
- [ ] https://www.ispreview.co.uk/index.php/2018/03/age-verification-uk-isp-internet-porn-ban-quietly-delayed.html
- [ ] https://www.theregister.co.uk/2018/03/26/bbfc_guidance_age_check_online_smut/
- [ ] YouTube gun ban drives bloggers to PornHub http://www.bbc.co.uk/news/technology-43500714
- [ ] https://torrentfreak.com/trump-promises-copyright-crackdown-as-doj-takes-aim-at-streaming-pirates-180308/
- [ ] http://www.wbur.org/news/2018/03/22/school-threats-suicide-prevention-tech
- [ ] https://www.techdirt.com/articles/20180325/00424039493/not-everything-needs-copyright-lawyers-flip-out-that-photos-taken-ai-may-be-public-domain.shtml

**facebook**
- [ ] https://www.polygon.com/2018/3/7/17091938/oculus-runtime-error-outage-rift-vr-facebook
- [ ] https://motherboard.vice.com/en_us/article/3kjzvk/facebook-cambridge-analytica-not-a-data-breach
- [ ] https://www.theguardian.com/news/2018/mar/19/where-is-mark-zuckerberg-facebook-ceo-cambridge-analytica-scandal
- [ ] https://theoutline.com/post/3994/it-is-weirdly-hard-to-steal-mark-zuckerbergs-trash
- [ ] https://blog.mozilla.org/firefox/facebook-container-extension/
- [ ] https://www.theregister.co.uk/2018/03/27/facebook_zuckerberg_rejects_mps_summons_sends_exec/
- [ ] https://www.theguardian.com/technology/2018/mar/27/uk-website-age-checks-create-facebook-porn-critics-warn
- [ ] https://www.theguardian.com/commentisfree/picture/2018/mar/25/an-apology-of-sorts-from-mark-zuckerberg
- [ ] https://techcrunch.com/2018/03/23/elon-musk-deletes-own-spacex-and-tesla-facebook-pages-after-deletefacebook/
- [ ] https://techcrunch.com/2018/03/23/facebook-knows-literally-everything-about-you/
- [ ] https://www.theregister.co.uk/2018/03/23/cambridge_analytica_ico_search_warrant_approved/
- [ ] https://twitter.com/chesh/status/977274039889690627/photo/1
- [ ] https://www.theverge.com/2018/3/30/17179100/facebook-memo-leaks-boz-andrew-bosworth
- [ ] http://nymag.com/selectall/2018/03/facebook-secretly-saved-videos-users-deleted.html
- [ ] https://www.theguardian.com/technology/2018/apr/03/facebook-apologises-storing-draft-videos-users-thought-deleted-bug-mark-zuckerberg-tim-cook

**local events**
- [ ] April 10 BradLUG - http://bradlug.co.uk/
- [ ] Apri 11 Badonkadonk - http://meetup.com/badonkadonk
- [ ] April 28 Bradford Coder Dojo - https://bradford-coderdojo.github.io/
- [ ] May 31 Feral Vector tickets are up for sale - http://feral-vector.com/
---- beware of scam eventbrites eg. https://www.eventbrite.com/o/atechupcom-15646132597

**Comment by ekoner** [comment]
Grindr leak is 404 - article available at https://www.buzzfeed.com/azeenghorayshi/grindr-hiv-status-privacy

**Comment by notshi** [comment]
thank you @ekoner - just saw this :}
