### ISSUE TITLE
graphics in video

### ISSUE THREAD

**Issue by notshi** [meatstuff/itstuff#2]
when using kdenlive, i couldn't find an option to just plonk in an image with a transparent background and move it around so i had to find the actual pixel dimension of the video (1920 x 1080), place the image where i want it to be and export the entire layer as a png.

this might explain why the images have a large transparent area :}

however, we have moved the camera angles again so these images may turn up over people's faces (haha) so unless we're ok with that, you may want to redo these steps ...or just find a way to move it around in kdenlive.

**Comment by GeekAnnoyed** [comment]
Hello, 
I think you're/we're looking for Affine, you "plonk" the graphic on the video track and then click in the bottom right or left hand corner of the track.
this will make a yellow over/underlay between the tracks.. change the transition type to Affine and ....
Tada!

![snapshot80](https://cloud.githubusercontent.com/assets/822758/16542540/99f2e098-40a4-11e6-9e7c-e46ea4c44813.png)
A screen shot is worth a thousand words.

there I'm sure is a better way of doing it.

**Comment by notshi** [comment]
fantastic, thank you!

i've just uploaded the s.w banner - should hopefully cover the whole screen. can't wait to watch the vid!
