### ISSUE TITLE
new site

### ISSUE THREAD

**Issue by notshi** [meatstuff/itstuff#21]
due to the previous server dying in between backups, blog posts went missing and the current site has not been updated to include the currents ones with @ekoner.

i apologise for this latency.

the site was built on an old framework that has since been upgraded - i am now in process of creating a new site for IT STUFF during my free time - a simple theme to start with but toppings added later ^.^=

- [x] Fix Feedburner (RSS) when new site reloads
- [x] Clean up posts (we have 61 backed up) for new layout
- [x] Recreate footer
- [x] Redesign landing page
- [x] Redesign individual post
- [x] Box up (end music, script, ogg) below fold
- [x] Create pixel ekoner
- [x] Push live when basic stuff is done
- [x] Add most current episodes + lost ones
- [x] Upload all eps to archive.org

**Comment by notshi** [comment]
am now wondering if i should be embedding the original script of each ep to the posts.

this will go under the main section, in its own section so i could even forgo the usual gubbins (summary) of each ep as the main post.

hmmm

i'm just a little hesitant at deciding anything right now as it'll affect the previous 61 posts' layout. gah.

**Comment by notshi** [comment]
there's already been one iteration in the past - we used to host things on mixcloud.com but later just focused on archive.org instead of uploading to both platforms. also saves me time.

due to this, have had to redesign things to accommodate past and newer content without it looking too bad. eh - i think it's ok if older posts look slightly off - for now anyways.

just give us a shout if you see things looking wonky? thanks in advance, everyone :}

**Comment by notshi** [comment]
by the way - the main change of this entire process is that:

**this is no longer a dynamic site.**

we are now a static site! this means, backups are more reliable and we can host it anywhere :dagger: 

down side - i can no longer update it on the move (sometimes on the phone :P )

**Comment by notshi** [comment]
just realised the 2013 broadcasts do not exist in archive.org

also, we don't seem to have the very first broadcast (in 2013) on the website so have 'recreated' a post.


edit: ignore that - looks like *some of the* broadcasts do exist in archive.org but there is no post found on any websites about it.

**Comment by notshi** [comment]
holy shit - all eps are in - we are now UP TO FECKING DATE :sob:

**Comment by ekoner** [comment]
Woot!

**Comment by notshi** [comment]
technically, the new site is done - i'm quite happy with the way it looks at this stage.

once the feeds are fixed and added, it'll go live :}

**Comment by notshi** [comment]
new site is live - blog post urls need fixing but otherwise, we're good and up-to-date :D 

http://itstuff.org.uk <---- go look!
