### ISSUE TITLE
Image request, "This is bad tech advice" bannner

### ISSUE THREAD

**Issue by GeekAnnoyed** [meatstuff/itstuff#3]
Hello,
Would it be possible to have a "this is bad technology advice" banner.
I was thinking something thin just to pop at the bottom of the screen

**Comment by notshi** [comment]
sounds good. i'll probably add a few of these random banners so let's see how this one works and fits in the vidya

https://github.com/meatstuff/itstuff/blob/master/bad_advice.png

**Comment by GeekAnnoyed** [comment]
thank you that was perfect
