### ISSUE TITLE
World of Stuff Banner

### ISSUE THREAD

**Issue by GeekAnnoyed** [meatstuff/itstuff#5]
Hello, 

Would it be possible to have some kinda world of stuff banner @notshi 
I just noticed while editing that is is one thing we're lacking :+1:

**Comment by notshi** [comment]
ooh, that's true. came up with this for now - hope it's okay!

![wos](https://cloud.githubusercontent.com/assets/1515961/17270889/5d52e242-5665-11e6-9118-a896a6d5c190.png)

might have to replace the background image with a collage or something later.

**Comment by GeekAnnoyed** [comment]
that is perfect :)
just in time too
